// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using QuizyfyAPI.Data;
using QuizyfyAPI.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(QuizDbContext), typeof(QuizDbContextModel))]
