// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace QuizyfyAPI.Data.CompiledModels
{
    public partial class QuizDbContextModel
    {
        private QuizDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("d9e8646f-1dc0-470f-99bf-570365607a43"), entityTypeCount: 7)
        {
        }

        partial void Initialize()
        {
            var choice = ChoiceEntityType.Create(this);
            var image = ImageEntityType.Create(this);
            var like = LikeEntityType.Create(this);
            var question = QuestionEntityType.Create(this);
            var quiz = QuizEntityType.Create(this);
            var refreshToken = RefreshTokenEntityType.Create(this);
            var user = UserEntityType.Create(this);

            ChoiceEntityType.CreateForeignKey1(choice, question);
            LikeEntityType.CreateForeignKey1(like, quiz);
            QuestionEntityType.CreateForeignKey1(question, image);
            QuestionEntityType.CreateForeignKey2(question, quiz);
            QuizEntityType.CreateForeignKey1(quiz, image);
            RefreshTokenEntityType.CreateForeignKey1(refreshToken, user);

            ChoiceEntityType.CreateAnnotations(choice);
            ImageEntityType.CreateAnnotations(image);
            LikeEntityType.CreateAnnotations(like);
            QuestionEntityType.CreateAnnotations(question);
            QuizEntityType.CreateAnnotations(quiz);
            RefreshTokenEntityType.CreateAnnotations(refreshToken);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "10.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
