namespace QuizyfyAPI.Contracts.Requests;

/// <summary>
/// Request used to provide data for email verification.
/// </summary>
internal sealed record RecoverPasswordRequest
{
    /// <summary>
    /// Password Recovery token generated by guid.
    /// </summary>
    [Required]
    public required string Token { get; init; }

    [Required]
    public required string Password { get; init; }
}