using System.ComponentModel.DataAnnotations;

namespace QuizyfyAPI.Contracts.Responses;

/// <summary>
/// Request used to provide data for email verification.
/// </summary>
public record VerifyEmailRequest
{
    /// <summary>
    /// Email verification token generated by guid.
    /// </summary>
    [Required]
    public required string Token { get; init; }
}