namespace QuizyfyAPI.Contracts.Responses;
/// <summary>
/// Request used to provide data for email verification.
/// </summary>
public class VerifyEmailRequest
{
    /// <summary>
    /// Email verification token generated by guid.
    /// </summary>
    public string Token { get; set; } = null!;
}
